class Feature:

    # 1.1. original
    FEAT_booking_id = 'bookingID'
    FEAT_accuracy = 'Accuracy'
    FEAT_bearing = 'Bearing'
    FEAT_acceleration_x = 'acceleration_x'
    FEAT_acceleration_y = 'acceleration_y'
    FEAT_acceleration_z = 'acceleration_z'
    FEAT_gyro_x = 'gyro_x'
    FEAT_gyro_y = 'gyro_y'
    FEAT_gyro_z = 'gyro_z'
    FEAT_second = 'second'
    FEAT_speed = 'Speed'

    TARGET = 'label'

    # 1.2. engineered (expansion)
    FEAT_valid_bearing = 'valid_bearing'
    FEAT_valid_speed = 'valid_speed'

    FEAT_scalar_acceleration = 'scalar_acceleration'
    FEAT_scalar_gyro = 'scalar_gyro'

    FEAT_deltasec = 'deltasec'
    FEAT_deltasec_bearing = 'deltasec_bearing'
    FEAT_deltasec_speed = 'deltasec_speed'

    FEAT_delta_scalar_gyro = 'delta_scalar_gyro'
    FEAT_delta_scalar_acceleration = 'delta_scalar_acceleration'
    FEAT_delta_bearing = 'delta_bearing'
    FEAT_delta_speed = 'delta_speed'
    FEAT_delta_acceleration_x = 'delta_acceleration_x'
    FEAT_delta_acceleration_y = 'delta_acceleration_y'
    FEAT_delta_acceleration_z = 'delta_acceleration_z'
    FEAT_delta_gyro_x = 'delta_gyro_x'
    FEAT_delta_gyro_y = 'delta_gyro_y'
    FEAT_delta_gyro_z = 'delta_gyro_z'

    # 1.3. engineered (aggregate)
    FEAT_percent_active = 'percent_active'
    FEAT_percent_active_bearing = 'percent_active_bearing'
    FEAT_percent_active_speed = 'percent_active_speed'

    FEAT_mean_accuracy = 'mean_accuracy'
    FEAT_best_accuracy = 'best_accuracy'
    FEAT_worst_accuracy = 'worst_accuracy'
    FEAT_stddev_accuracy = 'stddev_accuracy'

    FEAT_mean_bearing = 'mean_bearing'
    FEAT_stddev_bearing = 'stddev_bearing'
    FEAT_mean20_bearing = 'mean20_bearing'
    FEAT_stddev20_bearing = 'stddev20_bearing'
    FEAT_mean5_bearing = 'mean5_bearing'
    FEAT_stddev5_bearing = 'stddev5_bearing'
    FEAT_mean1_bearing = 'mean1_bearing'
    FEAT_stddev1_bearing = 'stddev1_bearing'

    FEAT_mean_speed = 'mean_speed'
    FEAT_stddev_speed = 'stddev_speed'
    FEAT_mean20_speed = 'mean20_speed'
    FEAT_stddev20_speed = 'stddev20_speed'
    FEAT_mean5_speed = 'mean5_speed'
    FEAT_stddev5_speed = 'stddev5_speed'
    FEAT_mean1_speed = 'mean1_speed'
    FEAT_stddev1_speed = 'stddev1_speed'

    FEAT_mean_acceleration_x = 'mean_acceleration_x'
    FEAT_stddev_acceleration_x = 'stddev_acceleration_x'
    FEAT_mean20_acceleration_x = 'mean20_acceleration_x'
    FEAT_stddev20_acceleration_x = 'stddev20_acceleration_x'
    FEAT_mean5_acceleration_x = 'mean5_acceleration_x'
    FEAT_stddev5_acceleration_x = 'stddev5_acceleration_x'
    FEAT_mean1_acceleration_x = 'mean1_acceleration_x'
    FEAT_stddev1_acceleration_x = 'stddev1_acceleration_x'

    FEAT_mean_acceleration_y = 'mean_acceleration_y'
    FEAT_stddev_acceleration_y = 'stddev_acceleration_y'
    FEAT_mean20_acceleration_y = 'mean20_acceleration_y'
    FEAT_stddev20_acceleration_y = 'stddev20_acceleration_y'
    FEAT_mean5_acceleration_y = 'mean5_acceleration_y'
    FEAT_stddev5_acceleration_y = 'stddev5_acceleration_y'
    FEAT_mean1_acceleration_y = 'mean1_acceleration_y'
    FEAT_stddev1_acceleration_y = 'stddev1_acceleration_y'

    FEAT_mean_acceleration_z = 'mean_acceleration_z'
    FEAT_stddev_acceleration_z = 'stddev_acceleration_z'
    FEAT_mean20_acceleration_z = 'mean20_acceleration_z'
    FEAT_stddev20_acceleration_z = 'stddev20_acceleration_z'
    FEAT_mean5_acceleration_z = 'mean5_acceleration_z'
    FEAT_stddev5_acceleration_z = 'stddev5_acceleration_z'
    FEAT_mean1_acceleration_z = 'mean1_acceleration_z'
    FEAT_stddev1_acceleration_z = 'stddev1_acceleration_z'

    FEAT_mean_gyro_x = 'mean_gyro_x'
    FEAT_stddev_gyro_x = 'stddev_gyro_x'
    FEAT_mean20_gyro_x = 'mean20_gyro_x'
    FEAT_stddev20_gyro_x = 'stddev20_gyro_x'
    FEAT_mean5_gyro_x = 'mean5_gyro_x'
    FEAT_stddev5_gyro_x = 'stddev5_gyro_x'
    FEAT_mean1_gyro_x = 'mean1_gyro_x'
    FEAT_stddev1_gyro_x = 'stddev1_gyro_x'

    FEAT_mean_gyro_y = 'mean_gyro_y'
    FEAT_stddev_gyro_y = 'stddev_gyro_y'
    FEAT_mean20_gyro_y = 'mean20_gyro_y'
    FEAT_stddev20_gyro_y = 'stddev20_gyro_y'
    FEAT_mean5_gyro_y = 'mean5_gyro_y'
    FEAT_stddev5_gyro_y = 'stddev5_gyro_y'
    FEAT_mean1_gyro_y = 'mean1_gyro_y'
    FEAT_stddev1_gyro_y = 'stddev1_gyro_y'

    FEAT_mean_gyro_z = 'mean_gyro_z'
    FEAT_stddev_gyro_z = 'stddev_gyro_z'
    FEAT_mean20_gyro_z = 'mean20_gyro_z'
    FEAT_stddev20_gyro_z = 'stddev20_gyro_z'
    FEAT_mean5_gyro_z = 'mean5_gyro_z'
    FEAT_stddev5_gyro_z = 'stddev5_gyro_z'
    FEAT_mean1_gyro_z = 'mean1_gyro_z'
    FEAT_stddev1_gyro_z = 'stddev1_gyro_z'

    FEAT_mean_scalar_gyro = 'mean_scalar_gyro'
    FEAT_stddev_scalar_gyro = 'stddev_scalar_gyro'
    FEAT_mean20_scalar_gyro = 'mean20_scalar_gyro'
    FEAT_stddev20_scalar_gyro = 'stddev20_scalar_gyro'
    FEAT_mean5_scalar_gyro = 'mean5_scalar_gyro'
    FEAT_stddev5_scalar_gyro = 'stddev5_scalar_gyro'
    FEAT_mean1_scalar_gyro = 'mean1_scalar_gyro'
    FEAT_stddev1_scalar_gyro = 'stddev1_scalar_gyro'

    FEAT_mean_scalar_acceleration = 'mean_scalar_acceleration'
    FEAT_stddev_scalar_acceleration = 'stddev_scalar_acceleration'
    FEAT_mean20_scalar_acceleration = 'mean20_scalar_acceleration'
    FEAT_stddev20_scalar_acceleration = 'stddev20_scalar_acceleration'
    FEAT_mean5_scalar_acceleration = 'mean5_scalar_acceleration'
    FEAT_stddev5_scalar_acceleration = 'stddev5_scalar_acceleration'
    FEAT_mean1_scalar_acceleration = 'mean1_scalar_acceleration'
    FEAT_stddev1_scalar_acceleration = 'stddev1_scalar_acceleration'

    # 1.4. utility
    UTIL_connect = '_'

    @classmethod
    def feat_at(cls, feat, at):
        return feat + cls.UTIL_connect + str(at)
